name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up C
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Run make test
        run: |
          make test
